version: '3'
services:
    app:
        restart: always
        build:
            context: .
            dockerfile: ./dockerConfig/docker/app.dockerfile
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
        environment:
          DB_PORT: "3306"
          DB_HOST: "mysql"
        ports:
            - "5173:5173"

    web:
      restart: always
      build:
        context: ./
        dockerfile: dockerConfig/docker/web.dockerfile
      working_dir: /var/www/html
      volumes:
        - '.:/var/www/html'
      ports:
        - "8000:80"
      depends_on:
        - app
      links:
        - app

    mysql:
        restart: always
        image: 'mysql/mysql-server'
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'homestead'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'verde'
            MYSQL_ROOT_HOST: '%'
        volumes:
            - 'appmysql:/var/lib/mysql'
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
        ports:
        - "3306:3306"

volumes:
    appmysql:
        driver: local
